# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FCRN' do
pod 'IQKeyboardManager', '~> 5.0.4'
pod 'MMDrawerController', '~> 0.6.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FCRN

  target 'FCRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FCRNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
